// <auto-generated />
using System;
using Book_Library_Manager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Book_Library_Manager.Migrations
{
    [DbContext(typeof(BookLibraryManagerContext))]
    [Migration("20240703152614_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Book_Library_Manager.Core.Models.Domain.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BorrowDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BorrowedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PublicationYear")
                        .HasColumnType("int");

                    b.Property<float>("ReadingProgress")
                        .HasColumnType("real");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2a84cd60-b527-4b00-8be9-7e89e24646eb"),
                            Author = "Robert C. Martin",
                            Genre = "Software Development",
                            ISBN = "9780132350884",
                            PublicationYear = 2008,
                            ReadingProgress = 0f,
                            Title = "Clean Code: A Handbook of Agile Software Craftsmanship"
                        },
                        new
                        {
                            Id = new Guid("35d8ef1e-a239-428a-ab2f-70dc6b7d6f37"),
                            Author = "Erich Gamma, Richard Helm, Ralph Johnson, John Vlissides",
                            Genre = "Software Design",
                            ISBN = "9780201633610",
                            PublicationYear = 1994,
                            ReadingProgress = 0f,
                            Title = "Design Patterns: Elements of Reusable Object-Oriented Software"
                        },
                        new
                        {
                            Id = new Guid("53ab61ef-3033-4310-a01b-9a7e320d243c"),
                            Author = "David Thomas, Andrew Hunt",
                            Genre = "Software Development",
                            ISBN = "9780135957059",
                            PublicationYear = 2019,
                            ReadingProgress = 0f,
                            Title = "The Pragmatic Programmer: Your Journey to Mastery"
                        },
                        new
                        {
                            Id = new Guid("e36604da-8649-47ab-8d7c-4262ee68a372"),
                            Author = "Thomas H. Cormen, Charles E. Leiserson, Ronald L. Rivest, Clifford Stein",
                            Genre = "Algorithms",
                            ISBN = "9780262033848",
                            PublicationYear = 2009,
                            ReadingProgress = 0f,
                            Title = "Introduction to Algorithms"
                        },
                        new
                        {
                            Id = new Guid("86683d0b-6ef5-4d0f-89e5-655fdb920605"),
                            Author = "Steve McConnell",
                            Genre = "Software Development",
                            ISBN = "9780735619678",
                            PublicationYear = 2004,
                            ReadingProgress = 0f,
                            Title = "Code Complete: A Practical Handbook of Software Construction"
                        },
                        new
                        {
                            Id = new Guid("d2865ede-8a82-465c-a811-0811897685e4"),
                            Author = "Martin Fowler",
                            Genre = "Software Development",
                            ISBN = "9780134757599",
                            PublicationYear = 2018,
                            ReadingProgress = 0f,
                            Title = "Refactoring: Improving the Design of Existing Code"
                        },
                        new
                        {
                            Id = new Guid("c886d7c4-d79d-4a82-aec5-232d6cdac8b7"),
                            Author = "Eric Freeman, Elisabeth Robson, Bert Bates, Kathy Sierra",
                            Genre = "Software Design",
                            ISBN = "9780596007126",
                            PublicationYear = 2004,
                            ReadingProgress = 0f,
                            Title = "Head First Design Patterns"
                        },
                        new
                        {
                            Id = new Guid("a58c7550-8641-455a-a3c6-bd9eef479e89"),
                            Author = "Robert C. Martin",
                            Genre = "Professional Development",
                            ISBN = "9780137081073",
                            PublicationYear = 2011,
                            ReadingProgress = 0f,
                            Title = "The Clean Coder: A Code of Conduct for Professional Programmers"
                        },
                        new
                        {
                            Id = new Guid("6e371271-478e-48a4-8483-706ef9182239"),
                            Author = "Gayle Laakmann McDowell",
                            Genre = "Interview Preparation",
                            ISBN = "9780984782857",
                            PublicationYear = 2015,
                            ReadingProgress = 0f,
                            Title = "Cracking the Coding Interview"
                        },
                        new
                        {
                            Id = new Guid("b0243205-b3e8-4d1a-b344-c981de69587c"),
                            Author = "Eric Evans",
                            Genre = "Software Architecture",
                            ISBN = "9780321125217",
                            PublicationYear = 2003,
                            ReadingProgress = 0f,
                            Title = "Domain-Driven Design: Tackling Complexity in the Heart of Software"
                        },
                        new
                        {
                            Id = new Guid("ec123f55-9b11-4e08-9e00-7e79a17b8485"),
                            Author = "Martin Fowler",
                            Genre = "Software Architecture",
                            ISBN = "9780321127426",
                            PublicationYear = 2002,
                            ReadingProgress = 0f,
                            Title = "Patterns of Enterprise Application Architecture"
                        },
                        new
                        {
                            Id = new Guid("0bc1b3da-bdda-4886-8ea7-7e8a05f5e7e0"),
                            Author = "Robert C. Martin",
                            Genre = "Agile Methodology",
                            ISBN = "9780135974445",
                            PublicationYear = 2002,
                            ReadingProgress = 0f,
                            Title = "Agile Software Development: Principles, Patterns, and Practices"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
