// <auto-generated />
using System;
using Book_Library_Manager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Book_Library_Manager.Migrations
{
    [DbContext(typeof(BookLibraryManagerContext))]
    partial class BookLibraryManagerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Book_Library_Manager.Core.Models.Domain.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BorrowDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BorrowedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PublicationYear")
                        .HasColumnType("int");

                    b.Property<float>("ReadingProgress")
                        .HasColumnType("real");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9419b39d-edf9-4b16-8124-8d9aeb1eac9e"),
                            Author = "Robert C. Martin",
                            Genre = "Software Development",
                            ISBN = "9780132350884",
                            PublicationYear = 2008,
                            ReadingProgress = 0f,
                            Title = "Clean Code: A Handbook of Agile Software Craftsmanship"
                        },
                        new
                        {
                            Id = new Guid("62eb1d22-0659-4ab4-9bfc-a5c381655d32"),
                            Author = "Erich Gamma, Richard Helm, Ralph Johnson, John Vlissides",
                            Genre = "Software Design",
                            ISBN = "9780201633610",
                            PublicationYear = 1994,
                            ReadingProgress = 0f,
                            Title = "Design Patterns: Elements of Reusable Object-Oriented Software"
                        },
                        new
                        {
                            Id = new Guid("2297c8ec-d67c-466b-9e31-85ec120855e0"),
                            Author = "David Thomas, Andrew Hunt",
                            Genre = "Software Development",
                            ISBN = "9780135957059",
                            PublicationYear = 2019,
                            ReadingProgress = 0f,
                            Title = "The Pragmatic Programmer: Your Journey to Mastery"
                        },
                        new
                        {
                            Id = new Guid("80c57645-ba8b-44e0-b002-db07a4150356"),
                            Author = "Thomas H. Cormen, Charles E. Leiserson, Ronald L. Rivest, Clifford Stein",
                            Genre = "Algorithms",
                            ISBN = "9780262033848",
                            PublicationYear = 2009,
                            ReadingProgress = 0f,
                            Title = "Introduction to Algorithms"
                        },
                        new
                        {
                            Id = new Guid("01b28c80-5d08-4ba8-bfcf-530e14eb1210"),
                            Author = "Steve McConnell",
                            Genre = "Software Development",
                            ISBN = "9780735619678",
                            PublicationYear = 2004,
                            ReadingProgress = 0f,
                            Title = "Code Complete: A Practical Handbook of Software Construction"
                        },
                        new
                        {
                            Id = new Guid("1cc74f2a-f42f-47e3-9db9-eaa8096446ff"),
                            Author = "Martin Fowler",
                            Genre = "Software Development",
                            ISBN = "9780134757599",
                            PublicationYear = 2018,
                            ReadingProgress = 0f,
                            Title = "Refactoring: Improving the Design of Existing Code"
                        },
                        new
                        {
                            Id = new Guid("f9ce84a1-9679-4012-ad7d-f17e257432b4"),
                            Author = "Eric Freeman, Elisabeth Robson, Bert Bates, Kathy Sierra",
                            Genre = "Software Design",
                            ISBN = "9780596007126",
                            PublicationYear = 2004,
                            ReadingProgress = 0f,
                            Title = "Head First Design Patterns"
                        },
                        new
                        {
                            Id = new Guid("5d759bd5-322f-4146-a9b5-18d1ef3d7771"),
                            Author = "Robert C. Martin",
                            Genre = "Professional Development",
                            ISBN = "9780137081073",
                            PublicationYear = 2011,
                            ReadingProgress = 0f,
                            Title = "The Clean Coder: A Code of Conduct for Professional Programmers"
                        },
                        new
                        {
                            Id = new Guid("8b4dd5bb-5e91-4db3-aa7a-5080f1534de9"),
                            Author = "Gayle Laakmann McDowell",
                            Genre = "Interview Preparation",
                            ISBN = "9780984782857",
                            PublicationYear = 2015,
                            ReadingProgress = 0f,
                            Title = "Cracking the Coding Interview"
                        },
                        new
                        {
                            Id = new Guid("82c45795-fed5-45f0-a7ac-115cda1babe1"),
                            Author = "Eric Evans",
                            Genre = "Software Architecture",
                            ISBN = "9780321125217",
                            PublicationYear = 2003,
                            ReadingProgress = 0f,
                            Title = "Domain-Driven Design: Tackling Complexity in the Heart of Software"
                        },
                        new
                        {
                            Id = new Guid("8895e33a-48ec-406c-8412-4f60d83f0e8d"),
                            Author = "Martin Fowler",
                            Genre = "Software Architecture",
                            ISBN = "9780321127426",
                            PublicationYear = 2002,
                            ReadingProgress = 0f,
                            Title = "Patterns of Enterprise Application Architecture"
                        },
                        new
                        {
                            Id = new Guid("f817f162-0c8d-4674-84d0-2eb7fd998f7f"),
                            Author = "Robert C. Martin",
                            Genre = "Agile Methodology",
                            ISBN = "9780135974445",
                            PublicationYear = 2002,
                            ReadingProgress = 0f,
                            Title = "Agile Software Development: Principles, Patterns, and Practices"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
